name: live_location
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  google_maps_flutter: ^2.2.0
  location: ^4.4.0
  flutter_svg: ^1.1.5
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
flutter_native_splash:
  image: "assets/splash_icon.png"
  color: "#ffffff"
  ios_content_mode: center

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  remove_alpha_ios: true